### ISSUE TITLE
Every boot it says "installing..."

### ISSUE THREAD

**Issue by Zullian** [KutsuyaYuki/ABG_extension#24]
Extension works just fine but each time I start SD I get this line:

Installing requirements for Web UI
Installing opencv-python for ABG_extension
Installing Pillow for ABG_extension

Idk why is that there every time when extensions works.

**Comment by Murlors** [comment]
I addressed it in https://github.com/KutsuyaYuki/ABG_extension/pull/23.

I think this is due to the following:

The `is_installed` function in `launch.py` uses the `importlib.util.find_spec` method, which is used to find the specification of a module, but it uses the package name as an argument in `install.py`, which should be the module name and not the package name.

**Comment by KutsuyaYuki** [comment]
I merged the pull request by @Murlors and this should be fixed now.
